### ISSUE TITLE
Android runtime linker missing symbol __emutls_get_address

### ISSUE THREAD

**Issue by Tereius** [wang-bin/mdk-sdk#49]
Hi,

I want to use mdk-sdk v0.14.0 in a Qt5 App on Android. I compiled Qt 5.15.2 with the Android NDK r21e. As soon as I start the App I can see a UnsatisfiedLinkError exception in Logcat:
```
2022-02-09 19:36:43.477 5606-5639/org.qtproject.example E/AndroidRuntime: FATAL EXCEPTION: qtMainLoopThread
    Process: org.qtproject.example, PID: 5606
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~E81EpQdeZGcLIpBfGIRNgQ==/org.qtproject.example-SDpDHEObWK1YiOGa1ak5-A==/lib/arm/libmdk.so"...
        at java.lang.Runtime.load0(Runtime.java:939)
        at java.lang.System.load(System.java:1628)
        at org.qtproject.qt5.android.QtNative$3.run(QtNative.java:473)
        at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
        at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
        at java.lang.Thread.run(Thread.java:923)
```

I suspect that it is because the App is bundled with an older libc++_shared from the NDK r21e than mdk-sdk (NDK r23b). Can you provide a release of mdk-sdk compiled with NDK r21e? Qt5 and 6 can't be compiled  with a NDK greater r22.

Thank you

**Comment by wang-bin** [comment]
try the latest build

**Comment by Tereius** [comment]
The latest mdk-sdk build works.

Thank you very much
